/* automatically generated by rust-bindgen 0.66.1 */

pub const CL_IOC_MAX_NODES: u32 = 1024;
pub const CL_IOC_MIN_NODE_ADDRESS: u32 = 1;
pub const CL_IOC_MAX_NODE_ADDRESS: u32 = 1023;
pub const CL_IOC_MAX_COMPONENTS_PER_NODE: u32 = 1024;
pub const CL_IOC_MIN_COMP_PORT: u32 = 1;
pub const CL_IOC_MAX_COMP_PORT: u32 = 1023;
pub const CL_IOC_RESERVED_PORTS: u32 = 64;
pub const CL_IOC_USER_RESERVED_PORTS: u32 = 64;
pub const CL_IOC_EPHEMERAL_PORTS: u32 = 896;
pub const CL_IOC_REASSEMBLY_TIMEOUT: u32 = 5000;
