/* automatically generated by rust-bindgen 0.66.1 */

pub const CL_VERSION_SHIFT: u32 = 24;
pub const CL_VERSION_MASK: u32 = 16777215;
pub const CL_RELEASE_VERSION_BASE: u32 = 4;
pub const CL_MAJOR_VERSION_BASE: u32 = 0;
pub const CL_MINOR_VERSION_BASE: u32 = 0;
pub const CL_RELEASE_VERSION: u32 = 4;
pub const CL_MAJOR_VERSION: u32 = 0;
pub const CL_MINOR_VERSION: u32 = 0;
pub const CL_RELEASE_VERSION_CURRENT: u32 = 6;
pub const CL_MAJOR_VERSION_CURRENT: u32 = 0;
pub const CL_MINOR_VERSION_CURRENT: u32 = 0;
